[package]
name = "duat-kak"
version = "0.3.0"
authors = ["AhoyISki"]
description = "A Kakoune inspired editing mode for Parsec"
repository = "https://github.com/AhoyISki/duat/tree/master/duat-kak"
license = "AGPL-3.0-or-later"
readme = "README.md"
keywords = ["editor", "editing-mode", "text", "duat"]
categories = ["command-line-utilities", "text-editors", "config"]
edition = "2024"

[dependencies]
# This dependency is taken as a submodule in order to allow
# me (AhoyISki) to edit duat and duat-core while also editing
# plugins at the same time, while still allowing for git
# dependencies when installing duat with the git-deps feature.
# If you are creating a plugin, you don't need to do this, just
# source duat-core from the repository if you want.
duat-core = { version = "0.3.0", path = "duat/duat-core/" }

# The same is happening here with duat-treesitter.
[dependencies.treesitter]
path = "duat-treesitter/"
version = "0.1.0"
package = "duat-treesitter"
