[package]
name = "duat-kak"
version = "0.5.1"
authors = ["AhoyISki"]
description = "A Kakoune inspired editing mode for Parsec"
repository = "https://github.com/AhoyISki/duat/tree/master/duat-kak"
license = "AGPL-3.0-or-later"
readme = "README.md"
keywords = ["editor", "editing-mode", "text", "duat"]
categories = ["command-line-utilities", "text-editors", "config"]
edition = "2024"

[dependencies]
duat-core = { version = "0.5.2", git = "https://github.com/AhoyISki/duat" }
duat-utils = { version = "0.2.0", git = "https://github.com/AhoyISki/duat" }

[dependencies.treesitter]
git = "https://github.com/AhoyISki/duat-treesitter"
version = "0.2.1"
package = "duat-treesitter"
